site_name: Affect
repo_url: https://github.com/MatthewMckee4/affect

nav:
- Home: index.md

theme:
  name: material
  locale: en
  palette:
    scheme: slate
    primary: cyan

  features:
  - navigation.instant
  - navigation.tabs
  - navigation.footer
  - navigation.indexes
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github

plugins:
- search
