name: Release

on:
  push:
    tags:
    - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  release-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11
    - name: Install build dependencies
      run: uv pip install build
    - name: Build distribution
      run: make build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.12.3

  release_github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install .
        pip freeze > requirements.txt
    - name: Publish Latest Draft
      run: |
        gh release edit ${{ github.ref_name }} --draft=false
        gh release upload ${{ github.ref_name }} requirements.txt --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: uv sync --all-extras
    - name: Build docs
      run: make docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
        publish_branch: gh-pages
        keep_files: false
        force_orphan: true
