name: Release

on:
  push:
    tags:
    - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  release_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        uv sync --all-extras
        uv pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        make build
        twine upload dist/*

  release_github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish Latest Draft
      run: |
        gh release edit ${{ github.ref_name }} --draft=false
        gh release upload ${{ github.ref_name }} --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: uv sync --all-extras
    - name: Build docs
      run: make docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
        publish_branch: gh-pages
        keep_files: false
        force_orphan: true
